export const HOBBIES = {
    read: {
          title: "",
        authorName: "",
      authorSurname: "",
      genre: "",
      dateOfPublication: "",
      authorBirthDate: "29/05/1970",
      bookImage: "",
      otherBooks: [
        {
          info: "",
        },
        {
          info: "",
        },
        {
          info: "",
        },
        {
          info: "",
        },
      ],
    },
    sports: [
      {
        name: "Football",
        indoor: false,
        favoriteTeam: "",
      },
      {
        name: "",
        indoor: false,
        favoriteTeam: "",
      },
      {
        name: "Football",
        indoor: true,
        favoriteTeam: "",
      },
    ],
    movies: [
      {
        name: "",
        type: "Movie/Serie",
        genre: "",
        vote: 9,
      },
     {
        name: "",
        type: "Movie/Serie",
        genre: "",
        vote: 0,
      },
    ],
    languages: {
      language: "English",
      wrlevel: "Native",
      splevel: "Native",
    },
    songsHeard: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    
  };